### ISSUE TITLE
Could not load dialog template from

### ISSUE THREAD

**Issue by mtcoliveira** [loftuxab/manual-manager#9]
I've installed the manual-manager in a alfresco 5.2 setup.
When i try to edit a topic i've the following error:

**Could not load dialog template from '/share/service/components/form?itemKind=node&itemId=workspace://SpacesStore/ce7a066d-14c0-4f56-b5d0-2951048418d3&destination={destination}&mode=edit&submitType=json&formId=manual-inline-edit&showCancelButton=true'.**

in Tomcat catalina log i've:

**Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.InternalInputBuffer.parseRequestLine(InternalInputBuffer.java:189)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1028)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)**

I need some help to fix this issue. Anybody can help me?

**Comment by mtcoliveira** [comment]
Just resolved the issue

Since Tomcat **7.0.76**, **8.0.42**, **8.5.12** you can define property requestTargetAllow to allow forbiden characters.

Add this line in your catalina.properties
`tomcat.util.http.parser.HttpParser.requestTargetAllow=|{}`
